### PR TITLE
feat: added event 'started'

### PR DESCRIPTION
**Pull request by jappyjan**
Hey man, really appreciate your plugin!
It saved me a lot of hassle when i realised that my touchscreen (spi) does interfere with the neopixels...

So im now trying to help you improve this plugin further!

As a first step i added the "started" event to add effects when a print is starting to print.
Also i did some minor refactoring

### CODE REVIEW

**Comment by jappyjan** [comment]
will try to add more of the features from your "todo" issue :)

**Comment by cp2004** [comment]
It would probably be easier to make each feature in separate PRs, so I can review them easier.

**Comment by jappyjan** [comment]
of course that is what im planning to do. just wanted to mention that i am working on more stuff :)

**Review by cp2004 — APPROVED** [review]
Made a couple of small changes, but other than that: Thank you! Also, this got me back into thinking about this plugin, so I'm working on it this weekend.

**Pull request merged**
